# -*- coding: utf-8 -*-
"""3

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RsvJXHSfjocTK68WGCOFID7mnajhiarK
"""

a = int(input())
if a == 1:
    print("Январь")
elif a == 2:
    print("Февраль")
elif a == 3:
    print("Апрель")
elif a == 4:
    print("Март")
elif a == 5:
    print("Май")
elif a == 6:
    print("Июнь")
elif a == 7:
    print("Июль")
elif a == 8:
    print("Август")
elif a == 9:
    print("Сентябрь")
elif a == 10:
    print("Ноябрь")
elif a == 11:
    print("Октябрь")
elif a == 12:
    print("Декабрь")
elif a > 12 or a < 1:
    print("Нет такого месяца")

a = int(input())
if a % 2 == 0:
    print("Четное")
else:
    print("Нечетное")

N = int(input())
if N > 40:
    print("Stonks")
elif N == 40:
    print("Neznayu")
else:
    print("Not stonks")

def is_year_leap(y):
  if y%4==0 and y%400==0 and y%100!=0:
    print('True')
  else:
    print('False')
y=int(input())
is_year_leap(y)

def is_prime(n):
  for i in range(2,int(n**0.5)):
    if n%i==0:
      return False
    return True
n=int(input())
print(is_prime(n))

a=int(input())
b=int(input())
c = [(-138 / 2) ** 1.3]
d = [abs((-69 / 28 ** 5.1) * 4)]
if a * 3.6 > b or (b in c and b in d):
    temp = a
    a = b
    b = temp

print("a =", a)
print("b =", b)

a = int(input())
b = int(input())
c = int(input())
n = ((a ** 2 + b ** 3) // c + 3) // 4
print(n)
if n % 2 == 0:
    print('chet')
else:
    print('nechet')